[tool.poetry]
name = "simple-platformer-game"
version = "0.1.0"
description = ""
authors = ["CatCoderr <catcoderr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
arcade = "^2.6.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

